In [17]:
import pandas as pd
df = pd.read_csv("../data/raw/Card_Aprov_Pre.csv")

In [19]:
df.head()

,Gênero,Idade,Dívida,Casado(a),Cliente do Banco,Setor da Indústria,Etnia,Anos Empregado,Inadimplência Anterior,Empregado(a),Pontuação de Crédito,Carteira de Motorista,Cidadania,Código Postal,Renda,Aprovado
0,1,30.83,0.000,1,1,7,4,1.25,1,1,1,0,0,202,0,1
1,0,58.67,4.460,1,1,9,1,3.04,1,1,6,0,0,43,560,1
2,0,24.50,0.500,1,1,9,1,1.50,1,0,0,0,0,280,824,1
3,1,27.83,1.540,1,1,7,4,3.75,1,1,5,1,0,100,3,1
4,1,20.17,5.625,1,1,7,4,1.71,1,0,0,0,1,120,0,1

In [21]:
import unicodedata

def limpar_coluna(col):
    col = ''.join(
        c for c in unicodedata.normalize('NFKD', col)
        if not unicodedata.combining(c)
    )
    return (
        col.strip()
        .lower()
        .replace(" ", "_")
        .replace("(", "")
        .replace(")", "")
    )

df.columns = [limpar_coluna(col) for col in df.columns]

In [23]:
df.head()

,genero,idade,divida,casadoa,cliente_do_banco,setor_da_industria,etnia,anos_empregado,inadimplencia_anterior,empregadoa,pontuacao_de_credito,carteira_de_motorista,cidadania,codigo_postal,renda,aprovado
0,1,30.83,0.000,1,1,7,4,1.25,1,1,1,0,0,202,0,1
1,0,58.67,4.460,1,1,9,1,3.04,1,1,6,0,0,43,560,1
2,0,24.50,0.500,1,1,9,1,1.50,1,0,0,0,0,280,824,1
3,1,27.83,1.540,1,1,7,4,3.75,1,1,5,1,0,100,3,1
4,1,20.17,5.625,1,1,7,4,1.71,1,0,0,0,1,120,0,1

In [25]:
colunas_binarias = ["aprovado", "empregadoa", "cliente_do_banco"]

for col in colunas_binarias:
    if df[col].dtype == "object":
        df[col] = df[col].map({
            "Sim": 1, "Não": 0,
            "Yes": 1, "No": 0
        })

In [26]:
df.to_csv("../data/processed/dados_limpos.csv", index=False)